### ISSUE TITLE
Game Freezes or Crashes on launch after update 3.4.1

### ISSUE THREAD

**Issue by Cazcy** [marzent/XIV-on-Mac#38]
after logging in when compiling shaders the game freezes or crashes. this started after updating to 3.4.1.

**Comment by seathasky** [comment]
Restart your mac, launch the game and let shaders recompile, we introduced new state cache today.

**Comment by Na1w** [comment]
Yes I had to remove the shader cache on my Macbook Air M1- or it freezes after shader compilation completed.
On my MacBook Pro M1 Max it does however run as expected without removing the cache.

**Comment by xwingfighter** [comment]
Seeing the same issue on my MacBook Air M1. I have to delete the cache file every time I try to launch the game or it freezes or crashes.

**Comment by Cazcy** [comment]
Thanks for the help! Where do I find this cache file I have to delete? I've looked through all the contents but can't find it.

**Comment by seathasky** [comment]
It looks like the cache state is causing some issues on M1. This is very unfortunate as the sole purpose is to reduce game stuttering. We saw a surge of users in our discord support channel, can somewhat confirm it's not happening on Intel Macs and only M1. We're looking into it!

**Comment by Na1w** [comment]
> Thanks for the help! Where do I find this cache file I have to delete? I've looked through all the contents but can't find it.

The cache file is inside the XIV on Mac.app/Contents/Resources/dxvk/ 

It only needs to be removed once, I have not notice any stuttering with this build at all so not sure it's necessary on the M1 at all. 
Personally I locked frame rates to 40 fps on the M1 Air (at 1440x900) as it seems to be a sweet spot where the game feels pretty smooth and the passive cooling manages to keep up dissipating the heat.

**Comment by seathasky** [comment]
> 

Yea if you had deleted the cache file you wouldn't notice the issue.

**Comment by ZoeyCluff** [comment]
> > Thanks for the help! Where do I find this cache file I have to delete? I've looked through all the contents but can't find it.
> 
> The cache file is inside the XIV on Mac.app/Contents/Resources/dxvk/
> 
> It only needs to be removed once, I have not notice any stuttering with this build at all so not sure it's necessary on the M1 at all. Personally I locked frame rates to 40 fps on the M1 Air (at 1440x900) as it seems to be a sweet spot where the game feels pretty smooth and the passive cooling manages to keep up dissipating the heat.


That folder is wrong. that'll brick the launcher. ~/Library/Application Support/XIV on Mac/game/drive_c is where the proper files are.

**Comment by Cazcy** [comment]
Thanks everyone I took that file out and I'm running smooth again!

**Comment by marzent** [comment]
Should be fixed with 593b467068cc53b51876947cce5d28cb8cf7e0a2

**Comment by Na1w** [comment]
> That folder is wrong. that'll brick the launcher. ~/Library/Application Support/XIV on Mac/game/drive_c is where the proper files are.

No it will not and it resolves the issue...



> Should be fixed with [593b467](https://github.com/marzent/XIV-on-Mac/commit/593b467068cc53b51876947cce5d28cb8cf7e0a2)

No this issue is still there.

**Comment by Na1w** [comment]
Video demonstrating the issue... (It's behaving exactly the same as before, it locks up when shader compilation is finished)
(And how removing the file base cache file in the directory- inside the launcher NOT in the Wine bottle resolves the issue)

https://youtu.be/OGsJKQrzMqE
